name: Daily Fetch and Update

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時（JSTなら9時に調整必要）
  workflow_dispatch:      # 手動実行も可能

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run fetch and update
        run: python turfmap/fetch_and_update.py
      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --quiet || git commit -m "Auto update: fetch and update data"
          git push
          